Version "4.7.1"

Class DebrisCore : Actor
{
	Default
	{
		+MISSILE
		+NOBLOCKMAP
		+NOTAUTOAIMED
		+DROPOFF
		+NOTELEPORT
		+FORCEXYBILLBOARD
		+FLOORCLIP
		+MOVEWITHSECTOR
		+CANNOTPUSH
		+SKYEXPLODE
		+NOBLOCKMONST
		+CANPASS
		
		+ROLLSPRITE +ROLLCENTER
	  
		-ACTIVATEIMPACT
		-ACTIVATEPCROSS
		
		Damage 0;
	}
}

#include "Actors/Tokens.zsc"
#include "Actors/Player.zsc"
#include "Actors/TitleMap.zsc"

#include "Actors/Cores/WeaponCore.zsc"
#include "Actors/Cores/MonsterCore.zsc"

////Effects, Particles, Debris

#include "Actors/Terrains.zsc"
#include "Actors/Particles.zsc"
#include "Actors/FloorDecals.zsc"
#include "Actors/Puffs.zsc"

#include "Actors/Debris/Gibs_Generic.zsc"

////Weapons

#Include "Actors/Weapons/Casings.zsc"

#Include "Actors/Weapons/Broom.zsc"
#Include "Actors/Weapons/Fists.zsc"
#Include "Actors/Weapons/Pistol.zsc"
#Include "Actors/Weapons/Shotgun.zsc"
#Include "Actors/Weapons/SuperShotgun.zsc"
#Include "Actors/Weapons/Rifle.zsc"
#Include "Actors/Weapons/Chaingun.zsc"
#Include "Actors/Weapons/RocketLauncher.zsc"
#Include "Actors/Weapons/PlasmaGun.zsc"
#Include "Actors/Weapons/BFG9000.zsc"
#Include "Actors/Weapons/Chainsaw.zsc"
#Include "Actors/Weapons/DumbWeapons.zsc"

////Items/PowerUps

#include "Actors/Pickups/Keys.zsc"
#include "Actors/Pickups/Ammo.zsc"
#include "Actors/Pickups/Armor.zsc"
#include "Actors/Pickups/Health.zsc"
#include "Actors/Pickups/Powerups.zsc"

////Monsters

#include "Actors/Monsters/Arachnotron.zsc"
#include "Actors/Monsters/ArchVile.zsc"
#include "Actors/Monsters/BaronHellKnight.zsc"
#include "Actors/Monsters/Cacodemon.zsc"
#include "Actors/Monsters/Imp.zsc"
#include "Actors/Monsters/PainAndLostSoul.zsc"
#include "Actors/Monsters/Mancubus.zsc"
#include "Actors/Monsters/ZombiePony.zsc"
#include "Actors/Monsters/ShotgunGuy.zsc"
#include "Actors/Monsters/HeavyWeaponDude.zsc"
#include "Actors/Monsters/BurstBat.zsc"
#include "Actors/Monsters/TechWeaponDudette.zsc"
#include "Actors/Monsters/Pinky.zsc"
#include "Actors/Monsters/Cyberdemon.zsc"
#include "Actors/Monsters/Revenant.zsc"
#include "Actors/Monsters/Canines.zsc"
#include "Actors/Monsters/ScriptedMarines.zsc"
#include "Actors/Monsters/SpiderMastermind.zsc"

////Props

#include "Actors/Props/Tech.zsc"
#include "Actors/Props/Nature.zsc"
#include "Actors/Props/Hell.zsc"
#include "Actors/Props/Gothic.zsc"
#include "Actors/Props/Gore.zsc"
#include "Actors/Props/Corpses.zsc"
#include "Actors/Props/ExplosiveBarrel.zsc"

#include "Actors/Props/Flat_Sprites/Flat_Facility.zsc"
#include "Actors/Props/Flat_Sprites/Flat_Blood.zsc"

#include "Actors/Props/Light_Sources/Light_Sources.zsc"
