Class EquestriaPlasmaGun : DoomEquestriaWeapon replaces PlasmaRifle
{
	Default
	{
		//$Title Plasma Gun
		Weapon.BobStyle "InverseSmooth";
		Weapon.SelectionOrder 100;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";

		Inventory.PickupMessage "$GOTPLASMA";
		Inventory.PickupSound "pickup/plasmagun";

		Tag "$TAG_PLASMARIFLE";
	}
	States
	{
	Spawn:
		PLAS A -1;
		Stop;
		
	Ready:
		TNT1 A 0 A_JumpIfInventory("KickCheck", 1, "Kick.Normal");

		PLSG A 1 A_WeaponReady();
		Loop;
	
	Select:
		PLSG A 0 A_SetCrossHair(12);
		
		PLSG A 1 A_Raise();
		Wait;
		
	Deselect:
		TNT1 A 0 A_TakeInventory("KickCheck", 999);
		
		PLSG A 1 A_Lower();
		Wait;
	
	Fire:
		TNT1 A 0 A_JumpIf(callACS("CamRecoilToggle")==1,"Fire.CamRecoil");
		
		PLSG A 1
		{
			A_FireProjectile("EquestriaPlasmaBall", 0, 0, 0, -8);
			A_FirePlasma();
		//	A_GunFlash();
		}
		PLSG A 2;
		PLSG A 0 A_ReFire();
		Goto Chill;
		
	Fire.CamRecoil:
		PLSG A 0 A_ZoomFactor(0.995);
		PLSG A 1
		{
			A_FireProjectile("EquestriaPlasmaBall", 0, 0, 0, -8);
			A_FirePlasma();
		//	A_GunFlash();
		}
		PLSG A 0 A_ZoomFactor(1);
		PLSG A 2;
		PLSG A 0 A_ReFire();

	Chill:
		PLSG B 1;
		PLSG CDE 1;
		PLSG F 12;
		PLSG EDCB 1;
		Goto Ready;
	
	Flash:
		//TNT1 A 0 A_Jump(90, 1, 2);
		//Wait;
		PLSF A 3 Bright
		{
			A_WeaponOffset(0, 40, WOF_KEEPX | WOF_INTERPOLATE);
			A_Light1();
		}
		Goto LightDone;
		PLSF B 3 Bright
		{
			A_WeaponOffset(0, 35, WOF_KEEPX | WOF_INTERPOLATE);
			A_Light1();
		}
		//I Don't know how i make a smooth animation with the original Doom Sprites
		Goto LightDone;
		
	Overlay.Aside:
		TNT1 A 0 A_OverlayFlags(3, PSPF_ADDBOB, true);
		TNT1 A 0 A_OverlayPivotAlign(3, PSPA_RIGHT, PSPA_BOTTOM);
		
		PLSG AFF 1
		{
			A_OverlayOffset(3, -35, 5, WOF_INTERPOLATE );
			A_OverlayRotate(3, 4, WOF_ADD);
		}
		PLSG FF 1
		{
			A_OverlayOffset(3, -30, 10, WOF_INTERPOLATE );
			A_OverlayRotate(3, 8, WOF_ADD);
		}
		PLSG F 10;
		PLSG FFF 1 
		{
			A_OverlayOffset(3, 0, 0, WOF_INTERPOLATE );
			A_OverlayRotate(3, -8, WOF_ADD);
		}
		PLSG A 1;
		Stop;
	
	Overlay.AirAside:
		TNT1 A 0 A_OverlayFlags(3, PSPF_ADDBOB, true);
		TNT1 A 0 A_OverlayPivotAlign(3, PSPA_RIGHT, PSPA_BOTTOM);
		
		PLSG AFF 1
		{
			A_OverlayOffset(3, -35, 5, WOF_INTERPOLATE );
			A_OverlayRotate(3, 5, WOF_ADD);
		}
		PLSG FF 1
		{
			A_OverlayOffset(3, -30, 10, WOF_INTERPOLATE );
			A_OverlayRotate(3, 10, WOF_ADD);
		}
		PLSG F 8;
		PLSG FFF 1 
		{
			A_OverlayOffset(3, 0, 0, WOF_KEEPY | WOF_INTERPOLATE );
			A_OverlayRotate(3, -10, WOF_ADD);
		}
		PLSG A 1;
		Stop;
		
	}
}
		
Class EquestriaPlasmaBall : PlasmaBall
{
	Default
	{
		Decal "PlasmaScorch";
		
		DamageType "Plasma";
		
		Radius 8;
		Height 16;
	  
		+ROLLSPRITE;
		+ROLLCENTER;
		
		+FORCEXYBILLBOARD;
	}
	States
	{
	Spawn:
		PLSS A 0;
		PLSS A 0 A_SetRoll(random(0, 359));
	Projectile:
		PLSS A 1 Bright
		{
			A_SpawnItemEx("PlasmaTrail");
			A_SetRoll((roll + 15), SPF_INTERPOLATE);
		}
		Loop;
 
	Death:
		PLSE A 0 A_SpawnItem("PlasmaFloorCheck");
		PLSE ABC 4 Bright;
		PLSE DE 4 A_FadeOut(0.1);
		Stop;
	}
}

Class TechPlasmaBall : EquestriaPlasmaBall
{
	Default
	{
		Radius 13;
		Height 8;
		
		FastSpeed 30;
	}
}

Class PlasmaTrail : Trails
{
	States
	{
	Spawn:
		PLSS A 0;
		PLSS A 0 A_SetRoll(random(0, 359));
		PLSS A 1 Bright A_FadeOut(0.1);
		Wait;
	}
}

Class PlasmaGunLight : Actor replaces PlasmaBall
{
	Default
	{
		Radius 0; Height 0; Speed 0; Damage 0;
		+NOINTERACTION
	}
	States
	{
	Spawn:
		TNT1 A 3;
		Stop;
	}
}