Class TitleMapProps : Actor
{
	Default
	{
		Speed 0;
		+NOGRAVITY; +FLOAT; +NOINTERACTION;
	}
}

Class TheHorse : TitleMapProps
{	
	Default
	{
		//$Category TitleMap and End Screens
		Scale 0.50;
	}
	States
	{
	Spawn:
		TMAP A -1;
		Stop;
	}
}

Class PoorImp : TitleMapProps
{	
	Default
	{
		//$Category TitleMap and End Screens
		Scale 0.35;
		+FORCEXYBILLBOARD
	}
	States
	{
	Spawn:
		TMAP B -1;
		Stop;
	}
}