Class EquestriaRevenant : Revenant replaces Revenant
{
	Default
	{
		+CASTSPRITESHADOW
	
		Radius 20; Height 60;
	}
	States
	{
	Missile:
		SKEL J 10 bright A_FaceTarget();
		SKEL K 10 A_SpawnProjectile("EquestriaRevenantTracer", 55, randompick(-8, 8));
		SKEL K 10 A_FaceTarget();
		Goto See;
	}
}

Class EquestriaRevenantTracer : RevenantTracer replaces RevenantTracer
{
	Default
	{
		RenderStyle "Normal";
		Alpha 1;
		
		+FORCEXYBILLBOARD;
		+DONTSEEKINVISIBLE;
	}
}
