#library "CVARs"
#include "zcommon.acs"

script "CamRecoilToggle" (void)
{
    SetResultValue(GetCVar("CamRecoilToggle"));
}

script "GoreToggle" (void)
{
    SetResultValue(GetCVar("GoreToggle"));
}

script "GibsStayForever" (void)
{
    SetResultValue(GetCVar("GibsStayForever"));
}

script "FlatDecals" (void)
{
    SetResultValue(GetCVar("FlatDecals"));
}

script "Muzzle_Style" (void)
{
    SetResultValue(GetCVar("Muzzle_Style"));
}
