#library "EquestriaThings.acs"
#include "zcommon.acs"

//Ragedox says: Hands off!

script "CheckClopper" enter
{
	if (GameType() == GAME_TITLE_MAP)
	
	terminate;
	if (CheckInventory("DEPistol") && CheckClass("HDoomPlayer") && CheckClass("HDoomMonster"))
	{
		Delay(120);
		
		TakeInventory("DEPistol", 999);
		HudMessage(s:"What..!?"; HUDMSG_TYPEON | HUDMSG_PLAIN, 1, CR_ICE, 1.5, 0.8, 0, 0.05);
		
		Delay (10);
		
		FadeTo (255, 0, 255, 1.0, 1.0); //Fade to Pink
		
		Delay (35);
		
		FadeTo (255, 255, 255, 1.0, 0.5); //Fade to White
		
		Delay (13);
		{
			/*GiveInventory ("HPistol", 1);
			
			Delay(1);*/
			
			ChangeLevel ("Map32", 0, CHANGELEVEL_NOINTERMISSION);
		}
	}
}

//Script "CheckBrutal" enter
//{
//	if (CheckClass("Doomer") && CheckClass("Melee_Attacks")

Script "HealthWarning_Warn" ENTER
{
	if (GetActorProperty (0, APROP_HEALTH) <= 25 && !CheckInventory("PlayerHealthWarning"))
	{
		LocalAmbientSound("player/healthwarning", 127);
		GiveInventory("PlayerHealthWarning", 1);
		SetHudSize(320,200,1);
		SetFont("SmallFont");
		HudMessage(l:"LOWHEALTHWARNING"; HUDMSG_FADEINOUT, 99, CR_RED, 160.0, 155.0, 1.0, 0.01, 1.0);
		delay(1);
		HudMessage(l:"LOWHEALTHWARNING"; HUDMSG_FADEINOUT, 99, CR_RED, 160.0, 145.0, 1.0, 0.01, 1.0);
		delay(1);
		HudMessage(l:"LOWHEALTHWARNING"; HUDMSG_FADEINOUT, 99, CR_RED, 160.0, 153.0, 1.0, 0.01, 1.0);
		delay(1);
		HudMessage(l:"LOWHEALTHWARNING"; HUDMSG_FADEINOUT, 99, CR_RED, 160.0, 150.0, 1.0, 0.01, 1.0);
	}
	delay(1);
	restart;
}