Class FlatProps : Actor
{
	Default
	{
	//$Category Wall Sprites
		+NOCLIP +NOGRAVITY +NOINTERACTION +FLATSPRITE  +NOTONAUTOMAP
		Height 40; Radius 20;
	}
}

Class Wall_FlatProps : FlatProps
{
	Default
	{
		-FLATSPRITE +WALLSPRITE
	}
}

Class ExplosiveWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		FLAT A -1;
		Stop;
	}
}

Class VoltageWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		FLAT B -1;
		Stop;
	}
}

Class RadiationWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		FLAT C -1;
		Stop;
	}
}