Class Wall_FlatProps : Actor
{
	Default
	{
		//$Category Wall Sprites
		+NOCLIP +NOGRAVITY +NOINTERACTION
		+FLATSPRITE 
		+NOTONAUTOMAP
		
		Height 40;
		Radius 20;
	}
}

Class ExplosiveWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		WALL A -1;
		Stop;
	}
}

Class VoltageWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		WALL B -1;
		Stop;
	}
}

Class RadiationWarning : Wall_FlatProps
{
	States
	{
	Spawn:
		WALL C -1;
		Stop;
	}
}