// ACS
#library "kick"
#include "zcommon.acs"

// Defines

// Scripts
Script "Kick" (void)
{
	str weapon = GetWeapon();
	if (StrICmp(weapon, "KickWeapon"))
	{
		SetPlayerProperty(0, 1, PROP_INSTANTWEAPONSWITCH);
		GiveInventory("KickWeapon", 1);
		GiveInventory("Kicking", 1);
		SetWeapon("KickWeapon");
		While (CheckInventory("Kicking"))
			Delay(1);
		SetWeapon(weapon);
		TakeInventory("KickWeapon", 1);
		Delay(3);
		SetPlayerProperty(0, 0, PROP_INSTANTWEAPONSWITCH);
	}
}

// Functions